CREATE TABLE IF NOT EXISTS bank_statements (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  reference VARCHAR(64) NOT NULL,
  statement_date DATE NULL,
  period_start DATE NULL,
  period_end DATE NULL,
  start_balance DECIMAL(12, 2) NOT NULL DEFAULT 0,
  end_balance DECIMAL(12, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_bank_statements_reference (reference)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
